### PR TITLE
add stereo launch files using ueye_cam

### PR DESCRIPTION
**Pull request by k-okada**
this launch file may change to use ueye pakcage, see https://github.com/tork-a/rtmros_nextage/issues/103 for discussion

### CODE REVIEW

**Comment by 130s** [comment]
+1. Merging since there's no test for it now. Hopefully users will test and debug if necessary.

@k-okada Do you have an idea of what kind of tests would be useful to check this feature?

**Comment by longjie** [comment]
Hi,

I traced the wiki tutorial for the stereo camera. I can caribrate the stereo camera, but I cannot get disparity image. I get following error when I ran image_view as wiki says:

```
average rate: 29.695
    min: 0.008s max: 0.058s std dev: 0.00832s window: 654
average rate: 29.698
    min: 0.012s max: 0.054s std dev: 0.00884s window: 646
stereo_image_proc: /tmp/buildd/ros-hydro-image-geometry-1.10.18-0precise-20140617-1428/src/stereo_camera_model.cpp:35: bool image_geometry::StereoCameraModel::fromCameraInfo(const CameraInfo&, const CameraInfo&): Assertion `left_.tfFrame() == right_.tfFrame()' failed.
average rate: 29.700
    min: 0.008s max: 0.058s std dev: 0.00821s window: 683
[stereo_image_proc-9] process has died [pid 29624, exit code -6, cmd /opt/ros/hydro/lib/stereo_image_proc/stereo_image_proc _approximate_sync:=True __name:=stereo_image_proc __log:=/home/tajima/.ros/log/1d817c9a-4029-11e4-81b0-000bab77d7b5/stereo_image_proc-9.log].
log file: /home/tajima/.ros/log/1d817c9a-4029-11e4-81b0-000bab77d7b5/stereo_image_proc-9*.log
average rate: 29.695
    min: 0.012s max: 0.054s std dev: 0.00871s window: 676
average rate: 29.699
```

And the log file says:

```
[ WARN] [1411150606.766314118]: Started in the global namespace! This is probably wrong. Start stereo_image_proc in the stereo namespace.
Example command-line usage:
    $ ROS_NAMESPACE=my_stereo rosrun stereo_image_proc stereo_image_proc
```

**Comment by k-okada** [comment]
sorry for late, you have update ueye_cam repository to include (https://github.com/anqixu/ueye_cam/pull/8), since both two camera must have same `frame_id` to calculate stereo.

**Comment by youtalk** [comment]
@longjie @k-okada After applying PR https://github.com/anqixu/ueye_cam/pull/8, frame_id related problem still happened.
So I fix it. https://github.com/anqixu/ueye_cam/pull/9

**Comment by youtalk** [comment]
After calibration, I'm trying to capture stereo and visualize its disparity. But I cannot configure good stereo parameters.
Does anyone have some advice?

**Comment by longjie** [comment]
Now I can get dispality images. Thank you @k-okada and @youtalk ! 
And I'm doing adjust stereo parameters and not succeeded yet.

**Comment by k-okada** [comment]
What's happens if you look at not near object, but far object, and set 
min_disparity to -16 or something

**Pull request merged**
