### PR TITLE
Start ROS clinent when the script begins

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by 130s** [comment]
Despite #145, I guess this particular PR is not tested so that we don't need to wait for travis.

**Comment by k-okada** [comment]
PR itself is tested on the travis and failing, is it ok for you?
https://travis-ci.org/tork-a/rtmros_nextage/builds/53606567

**Comment by 130s** [comment]
It is ok because test won't pass unless https://github.com/tork-a/rtmros_nextage/issues/131 is solved, and I verified that the test failing was expected.

**Comment by k-okada** [comment]
start fixeing in #146,  #131 said writeDigitalOutputWithMask should return False on simulation but it is not implement as you expected, it returns True https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L1284, should we change this behavior?

**Comment by 130s** [comment]
> writeDigitalOutputWithMask should return False on simulation but it is not implement as you expected, it returns True https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L1284, should we change this behavior?

Ideally returning false when no device is found sounds more reasonable. Can I change `HrpsysConfig.writeDigitalOutputWithMask` to return false with simulation?

**Comment by k-okada** [comment]
No problem for me

2015年3月16日月曜日、Isaac I.Y. Saitonotifications@github.comさんは書きました:

> writeDigitalOutputWithMask should return False on simulation but it is not
> implement as you expected, it returns True
> https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L1284,
> should we change this behavior?
> 
> Ideally returning false when no device is found sounds more reasonable.
> Can I change HrpsysConfig.writeDigitalOutputWithMask to return false with
> simulation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tork-a/rtmros_nextage/pull/146#issuecomment-81555848.

## 

## 

◉ Kei Okada

**Pull request merged**
