### PR TITLE
fix to make gazebo work

### PR DESCRIPTION
**Pull request by k-okada**
followup of #225, #223
## What is this

nextage simulation on gazebo + ros_control, this not exact simulation of real robot using hrpsys + rtmros, but good for rapid prototyping

```
gazebo + ros_control <-- JTA --> moveit <--> ros_client
hrpsys + rtmros  <-- JTA --> moveit <--> ros_clinet
```

Thus we can have moveit commander level compatibility between gazebo based simulation and hrpsys based simulation
## How to run simulation

```
roslaunch .nextaga_gazebo nextage_world.launch
roslaunch moveit_planning_execution.launch 
```
# How to control robot

Basically follow http://wiki.ros.org/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_MOVEIT instruction
# TODO
- implement set_pose_relative

```
[ERROR] [WallTime: 1472999902.699467] [889.309000] AcceptanceTestROS; set_pose_relative is not implemented yet
```
- go_init sometimes overshoot error/position tolerance, fix pid param of ros_control or include max effort

```
[INFO] [WallTime: 1472999963.273538] [949.428000] *** go_init begins ***
[ INFO] [1472999965.932903527, 952.065000000]: ABORTED: Solution found but controller failed during execution
[INFO] [WallTime: 1472999965.933587] [949.429000] '''(1)'''
```
- errors, may be ros acceptance test is not tested ?
- `_movegr_larm` is not defined , fixed inhttps://github.com/start-jsk/rtmros_hironx/pull/467/commits/288a167ff2e6cef4a4d7b1a2fd949d6b7ed81004#diff-857478fb2f83dd45b4a5fee7ca797b9cR330  ?

```
[INFO] [WallTime: 1472999768.663653] [756.760000] ROS ; larm
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-3597105e4678> in <module>()
----> 1 acceptance.run_tests_ros()

/home/k-okada/catkin_ws/ws_nextage/src/rtmros_hironx/hironx_ros_bridge/scripts/acceptancetest_hironx.py in run_tests_ros(self, do_wait_input)
    145                               before each task to proceed.
    146         '''
--> 147         self._run_tests(self._acceptance_ros_client, do_wait_input)
    148 
    149     def _run_tests(self, test_client, do_wait_input=False):

/home/k-okada/catkin_ws/ws_nextage/src/rtmros_hironx/hironx_ros_bridge/scripts/acceptancetest_hironx.py in _run_tests(self, test_client, do_wait_input)
    211         msg = _msg_type_client + msg_task
    212         self._wait_input(msg, do_wait_input)
--> 213         self._show_workspace(test_client)
    214 
    215     def _move_armbyarm_jointangles(self, test_client):

/home/k-okada/catkin_ws/ws_nextage/src/rtmros_hironx/hironx_ros_bridge/scripts/acceptancetest_hironx.py in _show_workspace(self, test_client)
    321         test_client.set_pose(
    322                    larm, self._POS_L_X_NEAR_Y_FAR, self._RPY_L_X_NEAR_Y_FAR,
--> 323                    msg + '{}'.format(larm), self._TASK_DURATION_DEFAULT, False)
    324         test_client.set_pose(
    325                    rarm, self._POS_R_X_NEAR_Y_FAR, self._RPY_R_X_NEAR_Y_FAR,

/home/k-okada/catkin_ws/ws_nextage/src/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/testutil/acceptancetest_ros.py in set_pose(self, joint_group, posision, rpy, msg_tasktitle, task_duration, do_wait, ref_frame_name)
     65         rospy.loginfo('ROS {}'.format(msg_tasktitle))
     66         self._robotclient.set_pose(joint_group, posision, rpy, task_duration,
---> 67                                    do_wait, ref_frame_name)
     68 
     69     def set_pose_relative(

/home/k-okada/catkin_ws/ws_nextage/src/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/ros_client.pyc in set_pose(self, joint_group, position, rpy, task_duration, do_wait, ref_frame_name)
    330         #
    331         # Check if MoveGroup is instantiated.
--> 332         if not self._movegr_larm or not self._movegr_rarm:
    333             try:
    334                 self._init_moveit_commanders()

/opt/ros/indigo/lib/python2.7/dist-packages/moveit_commander/robot.pyc in __getattr__(self, name)
    275             return self.Link(self, name)
    276         else:
--> 277             return object.__getattribute__(self, name)

AttributeError: 'ROS_Client' object has no attribute '_movegr_larm'
```
- need to look into
  [INFO] [WallTime: 1472999968.185162] [954.296000] ROS ; rarm
  [INFO] [WallTime: 1472999968.185915] [954.297000] setpose jntgr=rarm mvgr=<moveit_commander.move_group.MoveGroupCommander object at 0x7f40ce9db2d0> pose=[0.326, -0.472, 1.048, 3.073, -1.569, -3.072] posi=[0.326, -0.472, 1.048] rpy=[3.073, -1.569, -3.072]
  [ INFO] [1472999978.239465739, 964.156000000]: ABORTED: No motion plan found. No execution attempted.

```
```

### CODE REVIEW

**Comment by pazeshun** [comment]
@k-okada Please let me know why https://github.com/tork-a/rtmros_nextage/commit/4a2692c51b0503e03cb1cd339abda8ff377754dc and https://github.com/tork-a/rtmros_nextage/commit/392d9b484698284ebe4f9382705bc44cd8ab1843 are required, if you remember anything.
Now I'm making gazebo of HIRONXJSK, and wondering if I should follow those commits for setting HIRONXJSK's torque limits.
Even when I ran Nextage gazebo with reverting changes by those commits, I felt no difference.

**Comment by k-okada** [comment]
good question, may be I added this to pass the test. increase joint effort
more like to follow the commanded trajectories. But maybe we do not need
for your robot at this moment.
--
◉ Kei Okada



2020年4月26日(日) 13:56 Shun Hasegawa <notifications@github.com>:

**Comment by pazeshun** [comment]
Thank you very much for your valuable comment.
Now I understand I have to check result from follow_joint_trajectory_action and avoid execution failure:
```
$ rostopic echo /rarm_controller/follow_joint_trajectory_action/result 
WARNING: no messages received and simulated time is active.
Is /clock being published?
header: 
  seq: 0
  stamp: 
    secs: 6
    nsecs: 169000000
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 5
      nsecs: 958000000
    id: "/go_initial-1-5.958"
  status: 4
  text: ''
result: 
  error_code: -4
  error_string: ''
---
```
(even go_initial of nextage_gazebo fails, so I'll focus on execution after go_inital)
I'll make execution failure as rare as I can.

**Comment by pazeshun** [comment]
After measuring execution failure rate, I found that https://github.com/tork-a/rtmros_nextage/commit/4a2692c51b0503e03cb1cd339abda8ff377754dc and https://github.com/tork-a/rtmros_nextage/commit/392d9b484698284ebe4f9382705bc44cd8ab1843 make that rate very low (only 1 failure per 300 execution of 0.1 sec trajectory between [reset-pose](https://github.com/start-jsk/rtmros_tutorials/blob/34cd4d03556a6630c8e89058a24c96edd779edaa/hrpsys_ros_bridge_tutorials/models/hironxjsk.yaml#L42) and [reset-manip-pose](https://github.com/start-jsk/rtmros_tutorials/blob/34cd4d03556a6630c8e89058a24c96edd779edaa/hrpsys_ros_bridge_tutorials/models/hironxjsk.yaml#L45)).
I'll use torque limit values of those commits in HIRONXJSK.

**Pull request merged**
