### PR TITLE
kinematics_ikfast.yaml : no ik fast plugin for head and torso

### PR DESCRIPTION
**Pull request by k-okada**
current setup outputs following error, which make sence because we do not created ikfast plugin for head and torso, so use kdl

```
[ INFO] [1472919450.530481088, 53.710000000]: LARM_JOINT4 -1.74533 1.74533 1
[ INFO] [1472919450.530503958, 53.710000000]: LARM_JOINT5 -2.84489 2.84489 1
[FATAL] [1472919450.542292382, 53.730000000]: Joint numbers mismatch: URDF has 2 and IKFast has 6
[ERROR] [1472919450.542426915, 53.730000000]: Kinematics solver of type 'nextage_right_arm_kinematics/IKFastKinematicsPlugin' could not be initialized for group 'head'
[ERROR] [1472919450.542665573, 53.730000000]: Kinematics solver could not be instantiated for joint group head.
[FATAL] [1472919450.551285289, 53.735000000]: Joint numbers mismatch: URDF has 1 and IKFast has 6
[ERROR] [1472919450.551665721, 53.740000000]: Kinematics solver of type 'nextage_left_arm_kinematics/IKFastKinematicsPlugin' could not be initialized for group 'torso'
[ERROR] [1472919450.551711005, 53.740000000]: Kinematics solver could not be instantiated for joint group torso.
[ INFO] [1472919450.661796446, 53.845000000]: Starting scene monitor
```

c.f. #187

### CODE REVIEW

**Comment by k-okada** [comment]
@ros-pull-request-builder restart

**Comment by 130s** [comment]
Check by ROS buildfarm is now removed (see https://github.com/tork-a/rtmros_nextage/issues/249#issuecomment-244577779) so having Travis passed is enough for merging.

**Comment by k-okada** [comment]
i first thought the benefit of using ikfast is it output exact solution, but it turned out it also has some errors, interestingly kdl also have better result and ikfast has 0 error on x axis, that make sence.

ikfast

```
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.11762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
[ INFO] [1472930570.751434024]: Loading robot model 'NextageOpen'...
[ INFO] [1472930571.962903220, 11202.849999673]: Ready to take MoveGroup commands for group right_arm.
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.11762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(2)', [0.3255751238415409, -0.18236370422676493, 0.11762060609212988], (3.0746928728314296, -1.5690227687970997, -3.074502885856161))
('distance ', array([0.0000000000000000, -0.0000005641034468, -0.0000039165853411]))
```

kdl

```
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
[ INFO] [1472929931.295700374]: Loading robot model 'NextageOpen'...
[ INFO] [1472929932.513048871, 10562.049999776]: Ready to take MoveGroup commands for group right_arm.
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(2)', [0.3255730097171764, -0.18236308236977763, 0.06862441682673226], (3.072108145489664, -1.5690224285951122, -3.071918571014324))
('distance ', array([-0.0000021141243645, 0.0000000577535405, 0.0009998941492613]))
```

hrpsys

```
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.11762452267747121], (3.073437029206982, -1.5690226177313635, -3.0732470442069992))
('RARM', None, [0.3255751238415409, -0.18236314012331808, 0.11762452267747121], (3.073437029206982, -1.5690226177313635, -3.0732470442069992), 5)
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.11762452267747121], (3.073437029206982, -1.5690226177313635, -3.0732470442069992))
('RARM_JOINT5(2)', [0.325588744335197, -0.18236733539214042, 0.11754663310315672], (3.06960895771152, -1.569016253860755, -3.069421258283058))
('distance ', array([0.0000136204936561, -0.0000041952688223, -0.0000778895743145]))
```

code:

```
#!/usr/bin/env python


import rospy, sys, math, numpy, copy

from nextage_ros_bridge import nextage_client

def solve_ik_and_go(pos, rpy, tm=5):
    nxc.setTargetPose('RARM', pos, rpy, tm)
    nxc.waitInterpolationOfGroup('RARM')

def solve_ik_and_go_ikfast(pos, rpy, tm=1):
    from geometry_msgs.msg import Pose, PoseStamped
    from moveit_commander import MoveGroupCommander
    from moveit_msgs.srv import GetPositionIK, GetPositionIKRequest, GetPlanningScene, GetPlanningSceneRequest
    from moveit_msgs.msg import PositionIKRequest, PlanningSceneComponents, Constraints, RobotState
    from tf.transformations import quaternion_from_euler

    mg = MoveGroupCommander('right_arm')
    pose = PoseStamped()
    pose.header.frame_id = '/WAIST'
    pose.pose.position.x = pos[0]
    pose.pose.position.y = pos[1]
    pose.pose.position.z = pos[2]
    q = quaternion_from_euler(rpy[0],rpy[1],rpy[2])
    pose.pose.orientation.x = q[0]
    pose.pose.orientation.y = q[1]
    pose.pose.orientation.z = q[2]
    pose.pose.orientation.w = q[3]
    target_pose = []
    try:
        # robot state
        rospy.wait_for_service('/get_planning_scene')
        get_planning_scene = rospy.ServiceProxy('/get_planning_scene', GetPlanningScene)
        req = GetPlanningSceneRequest(components = PlanningSceneComponents(components = PlanningSceneComponents.ROBOT_STATE))
        robot_state =  get_planning_scene.call(req).scene.robot_state
        # ik
        rospy.wait_for_service('/compute_ik')
        compute_ik = rospy.ServiceProxy('/compute_ik', GetPositionIK)
        req = GetPositionIKRequest(ik_request = PositionIKRequest(
            group_name = 'right_arm', 
            avoid_collisions = True,
            constraints = Constraints(),
            robot_state = robot_state,
            timeout = rospy.Duration(1),
            pose_stamped = pose))
        res = compute_ik.call(req)
        if res.error_code.val != 1:
            raise Exception('ik failed')
        for i in [res.solution.joint_state.name.index(j) for j in  mg.get_active_joints()]:
            target_pose.append(res.solution.joint_state.position[i]*180/math.pi)

        nxc.setJointAnglesOfGroup('RARM', target_pose, tm)
    except Exception, e:
        import sys
        print(e)
        sys.exit(1)


nxc = nextage_client.NextageClient()
nxc.init()
nxc.goInitial()
rospy.init_node('moveit_commander')
# get current pose
pos1 = nxc.getCurrentPosition('RARM_JOINT5')
rpy1 = nxc.getCurrentRPY('RARM_JOINT5')
# move eddf
pos1[2] += 0.05
print('RARM_JOINT5(1)', pos1, rpy1)
# solve ik and go
solve_ik_and_go(pos1, rpy1)
#solve_ik_and_go_ikfast(pos1, rpy1)
# get moved pose
pos2 = nxc.getCurrentPosition('RARM_JOINT5')
rpy2 = nxc.getCurrentRPY('RARM_JOINT5')
print('RARM_JOINT5(1)', pos1, rpy1)
print('RARM_JOINT5(2)', pos2, rpy2)
numpy.set_printoptions(formatter={'float_kind':'{:.16f}'.format})
print("distance ", numpy.array(pos2) - numpy.array(pos1))
```

**Comment by k-okada** [comment]
another example, to move very small distance

```

# get current pose
pos1 = nxc.getCurrentPosition('RARM_JOINT5')
rpy1 = nxc.getCurrentRPY('RARM_JOINT5')
print('RARM_JOINT5(1)', pos1, rpy1)
# move eef
pos_ = copy.copy(pos1)
pos_[2] += 0.0001
print('RARM_JOINT5(_)', pos_, rpy1)
# solve ik and go
#solve_ik_and_go(pos_, rpy1)
solve_ik_and_go_ikfast(pos_, rpy1)
# get moved pose
pos2 = nxc.getCurrentPosition('RARM_JOINT5')
rpy2 = nxc.getCurrentRPY('RARM_JOINT5')
print('RARM_JOINT5(1)', pos1, rpy1)
print('RARM_JOINT5(2)', pos2, rpy2)
numpy.set_printoptions(formatter={'float_kind':'{:.16f}'.format})
print("distance ", numpy.array(pos2) - numpy.array(pos1))
```

hrpsys

```
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(_)', [0.3255751238415409, -0.18236314012331808, 0.06772452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM', None, [0.3255751238415409, -0.18236314012331808, 0.06772452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053), 5)
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(2)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('distance ', array([0.0000000000000000, 0.0000000000000000, 0.0000000000000000]))
```

kdl

```
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(_)', [0.3255751238415409, -0.18236314012331808, 0.06772452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
[ INFO] [1472959676.661805465]: Loading robot model 'NextageOpen'...
[ INFO] [1472959677.806562878, 18970.199999371]: Ready to take MoveGroup commands for group right_arm.
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(2)', [0.3255751026990858, -0.18236313953611738, 0.06772452164813791], (3.0734237450834265, -1.5690226158493372, -3.0732337642213543))
('distance ', array([-0.0000000211424551, 0.0000000005872007, 0.0000999989706669]))
```

ikfast

```
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(_)', [0.3255751238415409, -0.18236314012331808, 0.06772452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
[ INFO] [1472959720.243242380]: Loading robot model 'NextageOpen'...
[ INFO] [1472959721.739985648, 19014.159999380]: Ready to take MoveGroup commands for group right_arm.
('RARM_JOINT5(1)', [0.3255751238415409, -0.18236314012331808, 0.06762452267747099], (3.0734370292070254, -1.5690226177313638, -3.073247044207053))
('RARM_JOINT5(2)', [0.3255751238415411, -0.18236381562960877, 0.06772060609225439], (3.0746928728314966, -1.5690227687970988, -3.074502885856272))
('distance ', array([0.0000000000000002, -0.0000006755062907, 0.0000960834147834]))
```

**Pull request merged**
