### PR TITLE
[nextage_ros_bridge] Fix path for catkin build

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
handlight test is failing

```
[nextage_ros_bridge.rosunit-test_nxo_handlight/test_handlight_l_04][FAILURE]----
True is not false
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_nextage/install/share/nextage_ros_bridge/test/test_handlight.py", line 106, in test_handlight_l_04
    self.assertFalse(result)
  File "/usr/lib/python2.7/unittest/case.py", line 414, in assertFalse
    raise self.failureException(msg)
--------------------------------------------------------------------------------
[nextage_ros_bridge.rosunit-test_nxo_handlight/test_handlight_r_02][FAILURE]----
True is not false
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_nextage/install/share/nextage_ros_bridge/test/test_handlight.py", line 82, in test_handlight_r_02
    self.assertFalse(result)
  File "/usr/lib/python2.7/unittest/case.py", line 414, in assertFalse
    raise self.failureException(msg)
--------------------------------------------------------------------------------
[nextage_ros_bridge.rosunit-test_nxo_handlight/test_handlight_r_04][FAILURE]----
True is not false
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_nextage/install/share/nextage_ros_bridge/test/test_handlight.py", line 90, in test_handlight_r_04
    self.assertFalse(result)
  File "/usr/lib/python2.7/unittest/case.py", line 414, in assertFalse
    raise self.failureException(msg)
--------------------------------------------------------------------------------
```

**Comment by 130s** [comment]
What's this for? `catkin_tools`?

Test error can be ignored. https://github.com/tork-a/rtmros_nextage/issues/131

**Comment by 130s** [comment]
Just a headsup, DEB of this package may or may not be released so soon because of https://github.com/tork-a/rtmros_nextage/issues/137

**Comment by garaemon** [comment]
In order to compile with `catkin build`, it use catkin_make_isolated automatically.
But according to isolated techniques, we cannot use xx_SOURCE_DIR, we need to use xx_SOURCE_PREFIX

**Pull request merged**
