### PR TITLE
Add a new launch file for real robot xtion/kinect camera

### PR DESCRIPTION
**Pull request by y-yosuke**
add a new launch file for real robot xtion/kinect camera.
https://github.com/y-yosuke/rtmros_nextage/blob/add_nextage_calibration/nextage_calibration/launch/nextage_kinect_xtion.launch

### CODE REVIEW

**Comment by 130s** [comment]
Can we omit `nextage_` prefix and use a bit more concise name for the launch file, like `kinect_xtion.launch`?
Majority of the usecase of launch files will be done via `roslaunch` with package name, so it's obvious that this launch file is for nextage.

Other than that +1. Automated tests on Travis passed.

**Comment by y-yosuke** [comment]
I changed the file name `nextage_kinect_xtion.launch` to `xtion_kinect.launch` .
The reason for starting with "xtion_" is that the launch option is openni2 starts for Xtion by default.

**Comment by 130s** [comment]
Could you remove `nextage_kinect_xtion.launch`?

>  The reason for starting with "xtion_" is that the launch option is openni2 starts for Xtion by default.

+1

**Comment by y-yosuke** [comment]
I removed `nextage_calibration/launch/nextage_kinect_xtion.launch` .

**Review by 130s — APPROVED** [review]

**Comment by 130s** [comment]
Squashed into a single commit https://github.com/tork-a/rtmros_nextage/commit/68347437dc072eedf39b5d041893c16a6cf51d78 (I should've done so upon merging).

**Comment by y-yosuke** [comment]
Thanks a lot. @130s

**Pull request merged**
