### PR TITLE
Add joystick launch

### PR DESCRIPTION
**Pull request by 130s**
While I already wrote [a tutorial for joystick](http://wiki.ros.org/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_GUI), looks like I haven't uploaded this file yet.

Originally introduced in [MoveIt! forum](https://groups.google.com/d/msg/moveit-users/lbUwNqiMuP8/DZX2Fn0EAQAJ).

### CODE REVIEW

**Comment by 130s** [comment]
The test with joy added in this PR will likely keep failing [like this](https://travis-ci.org/tork-a/rtmros_nextage/jobs/138969420#L6115-L6137) until next version of `moveit_ros` that includes https://github.com/ros-planning/moveit_ros/pull/691 will become available as DEB. 

For the record below is what I got from the test I did locally:

```
SUMMARY
========

PARAMETERS
 * /joy/autorepeat_rate: 40
 * /joy/coalesce_interval: 0.025
 * /joy/deadzone: 0.2
 * /joy/dev: /dev/input/js0
 * /joy_topic_hz/hz: 40.0
 * /joy_topic_hz/hzerror: 2.0
 * /joy_topic_hz/test_duration: 10.0
 * /joy_topic_hz/topic: /joy
 * /joy_topic_hz/wait_time: 15.0
 * /rosdistro: indigo
 * /rosversion: 1.11.19

NODES
  /
    joy (joy/joy_node)
    moveit_joy (moveit_ros_visualization/moveit_joy.py)

[ROSTEST]setup[/home/n130s/data/Dropbox/ROS/indigo_trusty/cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test] run_id[62c61976-370f-11e6-b877-80fa5b08d1d8] done
[ROSTEST]Running test [joy_topic_hz]
ROS_MASTER_URI=http://tork-kudu1:39877/
setting /run_id to 62c61976-370f-11e6-b877-80fa5b08d1d8
process[rosout-1]: started with pid [31681]
started core service [/rosout]
process[joy-2]: started with pid [31684]
[ROSTEST]tearDown[/home/n130s/data/Dropbox/ROS/indigo_trusty/cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test]
shutting down processing monitor...
[joy-2] killing on exit
[rosout-1] killing on exit
... shutting down processing monitor complete
[ROSTEST]rostest teardown /home/n130s/data/Dropbox/ROS/indigo_trusty/cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test complete
]]></system-out>
  <system-err><![CDATA[ERROR: cannot launch node of type [moveit_ros_visualization/moveit_joy.py]: can't locate node [moveit_joy.py] in package [moveit_ros_visualization]
]]></system-err>
</testsuite>
```

**Comment by 130s** [comment]
Although running `rostest` locally succeeds, Travis CI keeps failing at the `joy.test`.

```
$ rostest nextage_moveit_config joy.test 
... logging to /home/rospho/.ros/log/rostest-tork-kudu1-23491.log
[ROSUNIT] Outputting test results to /home/rospho/.ros/test_results/nextage_moveit_config/rostest-test_joy.xml
testjoy_topic_hz ... ok

[ROSTEST]-----------------------------------------------------------------------

[nextage_moveit_config.rosunit-joy_topic_hz/test_hz][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/rospho/.ros/log/rostest-tork-kudu1-23491.log
rospho@tork-kudu1:~/cws_hironxo/src/tork-a/rtmros_nextage$ more /home/rospho/.ros/test_results/nextage_moveit_config/rostest-test_joy.xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="unittest.suite.TestSuite" tests="1" time="12.039">
  <testcase classname="rostest.runner.RosTest" name="testjoy_topic_hz" time="12.0390"></testcase>
  <system-out><![CDATA[[ROSTEST]setup[/home/rospho//cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test] run_id[b2f5f39c-3969-11e6-8056-80fa5b08d1d8] star
ting
started roslaunch server http://tork-kudu1:40979/

SUMMARY
========

PARAMETERS
 * /joy/autorepeat_rate: 40
 * /joy/coalesce_interval: 0.025
 * /joy/deadzone: 0.2
 * /joy/dev: /dev/input/js0
 * /joy_topic_hz/hz: 40.0
 * /joy_topic_hz/hzerror: 2.0
 * /joy_topic_hz/test_duration: 10.0
 * /joy_topic_hz/topic: /joy
 * /joy_topic_hz/wait_time: 15.0
 * /rosdistro: indigo
 * /rosversion: 1.11.19

NODES
  /
    joy (joy/joy_node)
    moveit_joy (moveit_ros_visualization/moveit_joy.py)

[ROSTEST]setup[/home/rospho//cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test] run_id[b2f5f39c-3969-11e6-8056-80fa5b08d1d8] done
[ROSTEST]Running test [joy_topic_hz]
ROS_MASTER_URI=http://tork-kudu1:36893/
setting /run_id to b2f5f39c-3969-11e6-8056-80fa5b08d1d8
process[rosout-1]: started with pid [23519]
started core service [/rosout]
process[joy-2]: started with pid [23522]
process[moveit_joy-3]: started with pid [23541]
[ROSTEST]removing previous test results file [/home/rospho/.ros/test_results/nextage_moveit_config/rosunit-joy_topic_hz.xml]
[ROSTEST]Running test [joy_topic_hz]
ROS_MASTER_URI=http://tork-kudu1:36893/
setting /run_id to b2f5f39c-3969-11e6-8056-80fa5b08d1d8
process[rosout-1]: started with pid [23519]
started core service [/rosout]
process[joy-2]: started with pid [23522]
process[moveit_joy-3]: started with pid [23541]
[ROSTEST]removing previous test results file [/home/rospho/.ros/test_results/nextage_moveit_config/rosunit-joy_topic_hz.xml]
[ROSTEST]running test joy_topic_hz
process[joy_topic_hz-4]: started with pid [23554]
[joy_topic_hz-4] process has finished cleanly
log file: /home/rospho/.ros/log/b2f5f39c-3969-11e6-8056-80fa5b08d1d8/joy_topic_hz-4*.log
[ROSTEST]test [joy_topic_hz] finished
[ROSTEST]test [joy_topic_hz] results are in [/home/rospho/.ros/test_results/nextage_moveit_config/rosunit-joy_topic_hz.xml]
[ROSTEST]test [joy_topic_hz] results summary: 0 errors, 0 failures, 1 tests
[ROSTEST][ROSTEST] test [joy_topic_hz] done
[ROSTEST]tearDown[/home/rospho//cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test]
shutting down processing monitor...
[joy-2] killing on exit
[rosout-1] killing on exit
... shutting down processing monitor complete
[ROSTEST]rostest teardown /home/rospho//cws_hironxo/src/tork-a/rtmros_nextage/nextage_moveit_config/test/joy.test complete
]]></system-out>
  <system-err><![CDATA[[moveit_joy-3] process has died [pid 23541, exit code -11, cmd /opt/ros/indigo/lib/moveit_ros_visualization/moveit_joy.py __name:=moveit_joy __log:=/home/rospho/.ros/log/b2f5f39c-
3969-11e6-8056-80fa5b08d1d8/moveit_joy-3.log].
log file: /home/rospho/.ros/log/b2f5f39c-3969-11e6-8056-80fa5b08d1d8/moveit_joy-3*.log
]]></system-err>
</testsuite>
rospho@tork-kudu1:~/cws_hironxo/src/tork-a/rtmros_nextage$ more /home/rospho/.ros/log/b2f5f39c-3969-11e6-8056-80fa5b08d1d8/moveit_joy-3.log 
[rospy.client][INFO] 2016-06-23 10:41:22,369: init_node, name[/moveit_joy], pid[23541]
[xmlrpc][INFO] 2016-06-23 10:41:22,370: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-23 10:41:22,370: Started XML-RPC server [http://tork-kudu1:38727/]
[rospy.init][INFO] 2016-06-23 10:41:22,370: ROS Slave URI: [http://tork-kudu1:38727/]
[rospy.impl.masterslave][INFO] 2016-06-23 10:41:22,370: _ready: http://tork-kudu1:38727/
[xmlrpc][INFO] 2016-06-23 10:41:22,371: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-06-23 10:41:22,371: Registering with master node http://tork-kudu1:36893/
[rospy.init][INFO] 2016-06-23 10:41:22,470: registered with master
[rospy.rosout][INFO] 2016-06-23 10:41:22,471: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-23 10:41:22,473: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-23 10:41:22,474: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
rospho@tork-kudu1:~/cws_hironxo/src/tork-a/rtmros_nextage$ more /home/rospho/.ros/test_results/nextage_moveit_config/rosunit-joy_topic_hz.xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="unittest.suite.TestSuite" tests="1" time="10.123">
  <testcase classname="__main__.HzTest" name="test_hz" time="10.1231"></testcase>
  <system-out><![CDATA[Hz: 40.0
Hz Error: 2.0
Topic: /joy
Test Duration: 10.0
Waiting for messages
Starting rate measurement
Done waiting, validating results
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
rospho@tork-kudu1:~/cws_hironxo/src/tork-a/rtmros_nextage$ rospack find moveit_ros_visualization
/opt/ros/indigo/share/moveit_ros_visualization
```

I wonder [how `moveit_joy.py` is installed](http://answers.ros.org/question/224546/to-execute-modules-as-scripts-in-catkin/) is influencing or not.

**Comment by 130s** [comment]
Travis CI seems to fail at various locations in `moveit_joy.py`. Still not sure why.
- https://travis-ci.org/tork-a/rtmros_nextage/jobs/139635943#L6107
  
  ```
  -- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/catkin_ws/src/rtmros_nextage/nextage_moveit_config --package=nextage_moveit_config --results-filename test_joy.xml --results-base-dir /home/travis/catkin_ws/build/nextage_moveit_config/test_results /home/travis/catkin_ws/src/rtmros_nextage/nextage_moveit_config/test/joy.test 
  ... logging to /home/travis/.ros/log/rostest-testing-gce-f3a1d1d0-6097-4c88-9be6-773263d22f23-27299.log
  ... logging to /home/travis/.ros/log/rostest-testing-gce-f3a1d1d0-6097-4c88-9be6-773263d22f23-27298.log
  [ROSUNIT] Outputting test results to /home/travis/catkin_ws/build/nextage_moveit_config/test_results/nextage_moveit_config/rostest-test_joy.xml
  Traceback (most recent call last):
  File "/opt/ros/indigo/lib/moveit_ros_visualization/moveit_joy.py", line 44, in <module>
    from moveit_ros_planning_interface._moveit_robot_interface import RobotInterface
  KeyboardInterrupt
  ```
- https://travis-ci.org/tork-a/rtmros_nextage/jobs/139834751#L6114
  
  ```
  [ROSUNIT] Outputting test results to /home/travis/catkin_ws/build/nextage_moveit_config/test_results/nextage_moveit_config/rostest-test_joy.xml
  Traceback (most recent call last):
  File "/opt/ros/indigo/lib/moveit_ros_visualization/moveit_joy.py", line 43, in <module>
    import threading
  File "/usr/lib/python2.7/threading.py", line 1, in <module>
    """Thread module emulating a subset of Java's threading model."""
  KeyboardInterrupt
  [ROSUNIT] Outputting test results to /home/travis/catkin_ws/build/nextage_moveit_config/test_results/nextage_moveit_config/rostest-test_nxo_moveit.xml
  omniORB: Failed to bind to address :: port 2809. Address in use?
  omniORB: Error: Unable to create an endpoint of this description: giop:tcp::2809
  Failed to initialise the ORB / POA: INITIALIZE_TransportError
  Is omniNames already running?
  testjoy_topic_hz ... FAILURE!
  FAILURE: Test Fixture Nodes ['joy'] failed to launch
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
  --------------------------------------------------------------------------------
  [ROSTEST]-----------------------------------------------------------------------
  [testjoy_topic_hz][failed]
  ```

**Comment by k-okada** [comment]
are you really sure that you can run this test on local environment? I had following error

```
$ rostest joy.test 
... logging to /home/k-okada/.ros/log/rostest-kokada-t440s-29829.log
[ROSUNIT] Outputting test results to /home/k-okada/.ros/test_results/nextage_moveit_config/rostest-test_joy.xml
[ERROR] [1466724715.130697267]: Couldn't open joystick /dev/input/js0. Will retry every second.
testjoy_topic_hz ... ok

[ROSTEST]-----------------------------------------------------------------------

[nextage_moveit_config.rosunit-joy_topic_hz/test_hz][FAILURE]-------------------
no messages before timeout
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
    self.assert_(self.message_received, "no messages before timeout")
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1

```

**Comment by k-okada** [comment]
https://github.com/tork-a/rtmros_nextage/pull/247/files#diff-8ce82184be03f06d9c78a39fe8779a24R5 seems checking if `joy_node` publishing '/joy'. This test should be done withing "joy"  package....

Another Tips:

```
[ROSUNIT] Outputting test results to /home/travis/catkin_ws/build/nextage_moveit_config/test_results/nextage_moveit_config/rostest-test_joy.xml
Traceback (most recent call last):
File "/opt/ros/indigo/lib/moveit_ros_visualization/moveit_joy.py", line 44, in <module>
  from moveit_ros_planning_interface._moveit_robot_interface import RobotInterface
KeyboardInterrupt
```

did not mean that there is an error on `moveit_joy.py`, it tells you that TERM signal is sent when rostest stops and moveit_joy.py catch that test and stopped, I think...

**Comment by 130s** [comment]
I confirmed on a fresh docker image that the proposed test in this PR (until https://github.com/tork-a/rtmros_nextage/pull/247/commits/6f9cd7a565e1b4f61032772e02dc4effc892fae1) causes an error as follows (although the error seems different from https://github.com/tork-a/rtmros_nextage/pull/247#issuecomment-228216341).

```
root@a617591f077b:/tmp/cws_nxo# dpkg -p ros-indigo-moveit-ros-visualization|grep Ver                 
Version: 0.7.2-0trusty-20160621-035137-0700

root@a617591f077b:/tmp/cws_nxo# rostest nextage_moveit_config joy.test 
... logging to /root/.ros/log/rostest-a617591f077b-27335.log
[ROSUNIT] Outputting test results to /root/.ros/test_results/nextage_moveit_config/rostest-test_joy.xml
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/moveit_ros_visualization/moveit_joy.py", line 44, in <module>
    from moveit_ros_planning_interface._moveit_robot_interface import RobotInterface
KeyboardInterrupt
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
testjoy_topic_hz ... FAILURE!
FAILURE: Test Fixture Nodes ['joy'] failed to launch
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testjoy_topic_hz][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1

ERROR: The following tests failed to run:
 * testjoy_topic_hz

rostest log file is in /root/.ros/log/rostest-a617591f077b-16712.log
root@a617591f077b:/tmp/cws_nxo# pwd
/tmp/cws_nxo/src/rtmros_nextage/nextage_moveit_config/
root@a617591f077b:/tmp/cws_nxo/src/rtmros_nextage/nextage_moveit_config# git branch -vv
* add/joy_launch 6f9cd7a [origin/add/joy_launch] Add joystick launch (https://groups.google.com/d/msg/moveit-users/lbUwNqiMuP8/DZX2Fn0EAQAJ).
```

**Comment by 130s** [comment]
https://github.com/130s/rtmros_nextage/pull/8 is merged into this PR thanks to @k-okada

**Comment by k-okada** [comment]
You do not have to use fresh docker, just to remove joystick from your machine to fail test on your local environment 

And what happened in the error message is;
- Fail to run joy node, because joystick is not available either docker machine nor Travis machine 
- rostest send term signal to all nodes
- moveit_joy.py received that signal and terminate a program. It shows 'keyboard interrupt error' and somehow this program did not terminate cleanly

Thus message what you think error message is actually a message when it interrupted by a term signal. This is why each message differs.

## 

◉ Kei Okada

2016/06/25 11:01、Isaac I.Y. Saito notifications@github.com のメッセージ:

**Comment by 130s** [comment]
Travis passed. Merging.

I've never connected joystick device for this PR but test used to pass for me. Strange.

And, thank you for the hint. I think error message from joy py bettter be elaborated.

From [one of the error](https://travis-ci.org/tork-a/rtmros_nextage/jobs/139949303#L6107) previously happening:

```
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/moveit_ros_visualization/moveit_joy.py", line 44, in <module>
    from moveit_ros_planning_interface._moveit_robot_interface import RobotInterface
KeyboardInterrupt
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
```

[line 44](https://github.com/ros-planning/moveit_ros/blob/040c03a28b40906af62857a91241ab3f59e63ef7/visualization/python/moveit_ros_visualization/moveit_joy.py#L44) is:

```
from moveit_ros_planning_interface._moveit_robot_interface import RobotInterface
```

[`RobotInterface`](https://github.com/ros-planning/moveit_ros/blob/040c03a28b40906af62857a91241ab3f59e63ef7/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp#L56) takes `robot_description` but it wasn't passed, and RobotInterface either didn't return nor throw exception.

**Comment by k-okada** [comment]
On Sat, Jun 25, 2016 at 3:19 PM, Isaac I.Y. Saito notifications@github.com
wrote:

> RobotInterface
> https://github.com/ros-planning/moveit_ros/blob/040c03a28b40906af62857a91241ab3f59e63ef7/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp#L56
> takes robot_description but it wasn't passed, and RobotInterface either
> didn't return nor throw exception.

That's true, yes, you also forget to upload robot_description and robot_description_semantic , may be my comment is wrong, the signal comes from not rostest/roslaunch but moveit_joy.py and since that script running as multiple threads, so it look like the error differs every time.

## 

◉ Kei Okada

**Pull request merged**
