### PR TITLE
[NXO Client] Overridden getRTCList now simply calls a method from the parent class, HIRONX

### PR DESCRIPTION
**Pull request by 130s**
In order to return the same RTCs and utilize whatever the logic defined.

This PR is similar to #238 but the purpose is different.

### CODE REVIEW

**Comment by 130s** [comment]
This PR actually fixes a bug that we just found; currently there's no way for NXO to utilize `RemoveForceSensorLinkOffset` or `AbsoluteForceSensor` RTC (, which from `HIRONX` you can. See [here](https://github.com/start-jsk/rtmros_hironx/blob/afe78e916ce0f8125eea0a86e818ca31fce29d6e/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L252-L260)).

**Comment by 130s** [comment]
There seems to be [a temporary glitch on ROS buildfarm with some MoveIt! packages](http://repositories.ros.org/status_page/ros_indigo_default.html?q=moveit) so that the test is failing on Travis.

**Comment by 130s** [comment]
This PR seems to cause the following error.

```
$ ipython -i `rospack find nextage_ros_bridge`/script/nextage.py -- --host nextage
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
configuration ORB with nextage:15005
[hrpsys.py] waiting ModelLoader
[hrpsys.py] start hrpsys
[hrpsys.py] finding RTCManager and RobotHardware
[hrpsys.py]  waitForRTCManagerAndRoboHardware has renamed to waitForRTCManagerAndRoboHardware: Please update your code
[hrpsys.py] wait for RTCmanager : None
[hrpsys.py] wait for RobotHardware0 : <hrpsys.rtm.RTcomponent instance at 0x7f5693c8e290> ( timeout 0 < 10)
[hrpsys.py] findComps -> RobotHardware : <hrpsys.rtm.RTcomponent instance at 0x7f5693c8e290> isActive? = True
[hrpsys.py] simulation_mode : False
[hrpsys.py]  Hrpsys controller version info:
[hrpsys.py]    ms =  <hrpsys.rtm.RTCmanager instance at 0x7f5693c8e1b8>
[hrpsys.py]    ref =  <RTM._objref_Manager instance at 0x7f5693c8e320>
[hrpsys.py]    version  =  315.1.8
;;
;; Loading ImpedanceController < 315.1.9
;;
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/home/rosnoodle/cws_hironxo/src/tork-a/rtmros_nextage/nextage_ros_bridge/script/nextage.py in <module>()
     72     # This is backward compatible so that users can still keep using `nxc`.
     73     # See http://code.google.com/p/rtm-ros-robotics/source/detail?r=6926
---> 74     robot.init(robotname=args.robot, url=args.modelfile)
     75
     76     # ROS Client.

/home/rosnoodle/cws_hironxo/src/tork-a/rtmros_nextage/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.py in init(self, robotname, url)
    100         '''
    101         if not self.use_gazebo:
--> 102             HIRONX.init(self, robotname=robotname, url=url)
    103
    104     def get_hand_version(self):

/home/rosnoodle/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.pyc in init(self, robotname, url)
    313
    314         # all([rtm.findRTC(rn[0], rtm.rootnc) for rn in self.getRTCList()]) # not working somehow...
--> 315         if set([rn[0] for rn in self.getRTCList()]).issubset(set([x.name() for x in self.ms.get_components()])) :
    316             print(self.configurator_name + "hrpsys components are already created and running")
    317             self.findComps(max_timeout_count=0, verbose=True)

/home/rosnoodle/cws_hironxo/src/tork-a/rtmros_nextage/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.py in getRTCList(self)
    335                  of abbreviated and full names of the component.
    336         '''
--> 337         return HIRONX.getRTCList()
    338
    339     def goInitial(self, tm=7, wait=True, init_pose_type=0):

TypeError: unbound method getRTCList() must be called with HIRONX instance as first argument (got nothing instead)
```

**Comment by 130s** [comment]
Please review @k-okada 

Travis has been failing on unrelated tests.

**Comment by k-okada** [comment]
because of http://qiita.com/ynott/items/8acd03434569e23612f1 ?

## 

◉ Kei Okada

2016-10-13 7:35 GMT+09:00 Isaac I.Y. Saito notifications@github.com:

**Comment by 130s** [comment]
> Travis has been failing on unrelated tests.

Travis is failing at MoveIt! tests, which should be irrelevant with this PR.

**Comment by k-okada** [comment]
1 . did you run test code on you local machine? you can reproduce this error.
1. I'm not sure if this PR is the only cause, but I'm pretty sure that this PR brings at least one problem; you're using `super` (https://github.com/tork-a/rtmros_nextage/pull/239/files#diff-74831e17eddab0218a7f6d7fbc024a30R337
   ) with the object this is not inheritance of `object` class, see  HIRONX(https://github.com/start-jsk/rtmros_hironx/blob/indigo-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L221)    and HrpsysConfigurator (https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L161)
   which NextageClient avoid this issue with very tentative way (https://github.com/tork-a/rtmros_nextage/blob/indigo-devel/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.py#L46)

```
The model was successfully loaded ! 
Traceback (most recent call last):
  File "/home/travis/catkin_ws/install/share/nextage_ros_bridge/script/nextage.py", line 74, in <module>
    robot.init(robotname=args.robot, url=args.modelfile)
  File "/home/travis/catkin_ws/install/lib/python2.7/dist-packages/nextage_ros_bridge/nextage_client.py", line 109, in init
    HIRONX.init(self, robotname=robotname, url=url)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/hironx_ros_bridge/hironx_client.py", line 315, in init
    if set([rn[0] for rn in self.getRTCList()]).issubset(set([x.name() for x in self.ms.get_components()])) :
  File "/home/travis/catkin_ws/install/lib/python2.7/dist-packages/nextage_ros_bridge/nextage_client.py", line 344, in getRTCList
    return super(HIRONX, self).getRTCList()
TypeError: must be type, not classobj
```

**Comment by k-okada** [comment]
I have created https://github.com/fkanehiro/hrpsys-base/pull/1048, but not
sure if this code is ok with old python used in qnx, please check that, we
may be better to chenge HIRONX class

## 

◉ Kei Okada

2016-10-15 11:31 GMT+09:00 Isaac I.Y. Saito notifications@github.com:

**Comment by 130s** [comment]
@k-okada thank you for taking a look.
I found that in NextageClient there's already [an example of an "inherited" method](https://github.com/tork-a/rtmros_nextage/blob/c45969d18b09091c5213b32dfe0e1be6eed14bd5/nextage_ros_bridge/src/nextage_ros_bridge/nextage_client.py#L109), so I just did the same and Travis passed with the updated commit.

**Comment by k-okada** [comment]
nice ,this seems better solution.

**Comment by k-okada** [comment]
If
```
NXO -> custom hand
Hiro -> servo hand
```
is true, please consider reverting this, this causes the problem like #308

**Pull request merged**
