### PR TITLE
[travis] Use install target

### PR DESCRIPTION
**Pull request by 130s**
https://github.com/tork-a/rtmros_nextage/pull/191#issuecomment-148979058

### CODE REVIEW

**Comment by k-okada** [comment]
```
Get:138 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main python-decorator all 3.4.0-2build1 [19.2 kB]
Get:139 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-updates/main python-pexpect all 3.1-1ubuntu0.1 [37.8 kB]
Get:140 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main python-simplegeneric all 0.8.1-1 [11.5 kB]
Get:141 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/universe ipython all 1.2.1-2 [588 kB]
Get:142 http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/universe libconstantine-java all 0.7-5 [231 kB]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-updates/main libdbus-1-dev amd64 1.6.18-0ubuntu4.3
  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 91.189.92.200 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main libshout3 amd64 2.3.1-3
  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 91.189.92.200 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/universe libstringtemplate-java all 3.2.1-1
  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 91.189.92.200 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main libasm3-java all 3.3.2-2
  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 91.189.92.200 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty/main libasm4-java all 4.1-3
  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 91.189.92.200 80]
```

network problem????

**Comment by 130s** [comment]
Looks like [travis passed without network error](https://travis-ci.org/tork-a/rtmros_nextage/builds/86337860). Where does that error message come from?

**Comment by k-okada** [comment]
I restarted Travis, the message was from previous Travis run.
2015年10月21日水曜日、Isaac I.Y. Saitonotifications@github.comさんは書きました:

> Looks like travis passed without network error
> https://travis-ci.org/tork-a/rtmros_nextage/builds/86337860. Where does
> that error message come from?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tork-a/rtmros_nextage/pull/196#issuecomment-149639223
> .

## 

## 

◉ Kei Okada

**Comment by 130s** [comment]
I see thank you. Merging.

**Comment by k-okada** [comment]
since we're now only testing on indigo and also we could not build newer deb file, so we're to move to indigo-branch and bump version to 0.7.0? 
Does 0.6.6 is the last version for hydro?

**Comment by 130s** [comment]
This and #191 are:
- reset on `hydro-devel` branch. 
- remain on the new default `indigo-devel` branch.

**Pull request merged**
