### PR TITLE
Add hands_ueye.launch for bringing up hand's ueye camera nodes.

### PR DESCRIPTION
**Pull request by longjie**

### CODE REVIEW

**Comment by 130s** [comment]
Thank you for the elaborated contribution. 
Can someone who's sitting by the NXO (or perhaps even Hiro) confirm this? @uesnaola @emijah?

**Comment by emijah** [comment]
@130s @longjie Sorry, but I'm not a ros guru. Could  you please tell me what I need to type to check this?

**Comment by 130s** [comment]
Here's a guess from just looking at the suggested code.

To run: You'd just simply run the 2 launch files (2nd one is what's added this time).

```
Ubuntu-terminal1$ roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch nameserver:=%HOSTNAME_QNX%

Ubuntu-terminal2$ roslaunch nextage_ros_bridge hands_ueye.launch
```

To check, 

```
Ubuntu-terminal3$ rostopic echo image_raw
```

And if the topics are published, that could be the success. 

Or for visually checking the result you can run rqt tool.

```
Ubuntu-terminal3$ rqt -s image_view &
```

And choose `image_raw` from the pulldown menu.

**Comment by longjie** [comment]
Sorry for late reply.
Actually you can get images by only launching hands_ueye.launch because the camera is nothing with the nextage controller.

**Comment by 130s** [comment]
@RyuYamamoto is working on this.

**Comment by 130s** [comment]
@RyuYamamoto confirmed that image from both hands' cameras are published. Actually The launch works out of the box. Thank you!

**Pull request merged**
